#This is the config, tweak settings to your liking


#Sends a message when someone joins for the first time, leave blank for none
firstJoin_message: '&a&l<player> &r&2joined the server for the first time! Say hello!'

#Sends a message when someone joins the server normally, leave blank for none
join_message: '&8<player> &7joined the server'
